using Microsoft.Xna.Framework;

namespace ToyConEngine
{
    public class ScriptImporterNode : Node
    {
        public string Script { get; set; } = "";

        public ScriptImporterNode()
        {
            Name = "Script";
            // No inputs or outputs by default, they are generated by the script
        }

        public override void Evaluate(GameTime gameTime) { }
    }
}